
name: Terraform Apply

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: '3e97cc07-1df9-4433-bc68-030a1a78b255'
      ARM_CLIENT_SECRET: 'bdc386aa-69db-441f-b620-c7095e9f9865'
      ARM_SUBSCRIPTION_ID: '3d133d92-97d4-4100-96d8-3a6e163da246'
      ARM_TENANT_ID: '14ad6a30-731f-42b0-8013-b85efecc3073'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
